fix: backslash in tagged template
lingui/swc-plugin pull request #125
Opened 2024-11-10 10:56 UTC by Jack-Works

This PR fixes `\n` being extracted to `\\n`.

2024-11-11 12:15 UTC, timofei-iatsenko requested changes
There two changes in the code, but only one test added. It seems there are cases which is not covered. 

The second case might be

```jsx
<Trans>{`Multiline\nstring`}</Trans>
```
 (please test it with and without fix, because i just took it from mi mind)

2024-11-11 12:15 UTC, timofei-iatsenko commented on src/ast_utils.rs
> +}
Could be done as a one-liner 

```rust
tpl.cooked.as_ref().unwrap_or(&tpl.raw).to_string()
```

Also, let's rename a function to 

`get_tpl_cooked_or_raw_string`

2024-11-12 16:29 UTC, Jack-Works commented
Hi @timofei-iatsenko thanks for the review, I have updated the PR and added one case, but I cannot fix that case. I tried 2 to 3 different ways but to fix that case it looks like I need to rewrite a lot.

2024-12-19 11:52 UTC, closed without merging

2024-12-19 11:52 UTC, Jack-Works commented
looks like the new major version no longer does anything to the strings in tagged templates, closed for now
https://js-lingui-git-next-crowdin.vercel.app/releases/migration-5#no-whitespace-cleaning-in-js-macros